[project]
name = 'Blockchain-Based-Decentralized-Exchange'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-listing]
path = 'contracts/asset-listing.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-verification]
path = 'contracts/user-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
